version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd neo-cycle-client
      - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
      - npm install
      - cd ../neo-cycle-lambda
      - cd ./SessionMaintainer
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/SessionMaintainer/Deploy.zip
      - cd ../ParkingRetriever
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/ParkingRetriever/Deploy.zip
      - cd ../ReservationMaker
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/ReservationMaker/Deploy.zip
      - cd ../ReservationCanceller
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/ReservationCanceller/Deploy.zip
      - cd ../StatusChecker
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/StatusChecker/Deploy.zip
      - cd ../ParkingNearbyRetriever
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/ParkingNearbyRetriever/Deploy.zip
      - cd ../UserInitializer
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/UserInitializer/Deploy.zip
      - cd ../ParkingRegisterer
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/ParkingRegisterer/Deploy.zip
      - cd ../UserMigrator
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/UserMigrator/Deploy.zip
      - cd ../PostAuthenticator
      - npm install
      - zip -r Deploy.zip ./
      - aws s3 mv ./Deploy.zip s3://neo-cycle-${ENVIRONMENT_NAME}-lambda/${CODEBUILD_BUILD_NUMBER}/PostAuthenticator/Deploy.zip
      - cd ../../neo-cycle-infra
      - aws cloudformation deploy
          --stack-name neo-cycle-${ENVIRONMENT_NAME}-lambda
          --template-file Lambda/api-gateway-lambda.yaml
          --parameter-overrides ObjectKeyPrefix=${CODEBUILD_BUILD_NUMBER}
          --capabilities CAPABILITY_AUTO_EXPAND
      - aws cloudformation deploy
          --stack-name neo-cycle-${ENVIRONMENT_NAME}-cognito-lambda
          --template-file Lambda/cognito-lambda.yaml
          --parameter-overrides ObjectKeyPrefix=${CODEBUILD_BUILD_NUMBER} EnvName=${ENVIRONMENT_NAME}
          --capabilities CAPABILITY_AUTO_EXPAND
      - cd ..
  build:
    commands:
      - cd neo-cycle-client
      - touch ./.env
      - echo VUE_APP_GOOGLE_API_KEY=${VUE_APP_GOOGLE_API_KEY} >> ./.env
      - npm run build:${ENVIRONMENT_NAME}
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - '**/*'
  base-directory: neo-cycle-client/dist
cache:
  paths:
    - /tmp/node_modules.tar