AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda for auto reservation

######################################################
# Parameters:
######################################################
Parameters:
  ObjectKeyPrefix:
    Type: String
  NameTag:
    Type: String
    Default: neo-cycle
    AllowedValues:
      - neo-cycle
  EnvName:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Enter profile.

######################################################
# Resources
######################################################
Resources:
  LambdaScheduleQueuer:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${NameTag}-${EnvName}-lambda
        S3Key: !Sub ${ObjectKeyPrefix}/ScheduleQueuer/Deploy.zip
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
          SCHEDULE_QUEUE_URL: !ImportValue
            Fn::Sub: ${NameTag}-${EnvName}-ScheduleQueueUrl
      FunctionName: !Sub ${NameTag}-${EnvName}-ScheduleQueuer
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-RoleScheduleQueuerArn
      Runtime: nodejs12.x
      Timeout: 900
      ReservedConcurrentExecutions: 10
      Layers: 
        - !Ref LambdaAutoReservationLayer

  LambdaDailyScheduleCreator:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${NameTag}-${EnvName}-lambda
        S3Key: !Sub ${ObjectKeyPrefix}/DailyScheduleCreator/Deploy.zip
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
      FunctionName: !Sub ${NameTag}-${EnvName}-DailyScheduleCreator
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-RoleDailyScheduleCreatorArn
      Runtime: nodejs12.x
      Timeout: 20
      ReservedConcurrentExecutions: 10
      Layers: 
        - !Ref LambdaAutoReservationLayer

  LambdaDailyScheduleQueuer:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${NameTag}-${EnvName}-lambda
        S3Key: !Sub ${ObjectKeyPrefix}/DailyScheduleQueuer/Deploy.zip
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
          DAILY_SCHEDULE_QUEUE_URL: !ImportValue
            Fn::Sub: ${NameTag}-${EnvName}-DailyScheduleQueueUrl
      FunctionName: !Sub ${NameTag}-${EnvName}-DailyScheduleQueuer
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-RoleDailyScheduleQueuerArn
      Runtime: nodejs12.x
      Timeout: 900
      ReservedConcurrentExecutions: 10
      Layers: 
        - !Ref LambdaAutoReservationLayer

  LambdaDailyScheduleQueueConsumer:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${NameTag}-${EnvName}-lambda
        S3Key: !Sub ${ObjectKeyPrefix}/DailyScheduleQueueConsumer/Deploy.zip
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
      FunctionName: !Sub ${NameTag}-${EnvName}-DailyScheduleQueueConsumer
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-RoleDailyScheduleQueueConsumerArn
      Runtime: nodejs12.x
      Timeout: 20
      ReservedConcurrentExecutions: 10
      Layers: 
        - !Ref LambdaAutoReservationLayer

  # ----------------------------------------------------
  # EventSourceMapping
  # ----------------------------------------------------
  LambdaDailyScheduleCreatorEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-ScheduleQueueArn
      FunctionName: !Ref LambdaDailyScheduleCreator

  LambdaDailyScheduleQueueConsumerEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-DailyScheduleQueueArn
      FunctionName: !Ref LambdaDailyScheduleQueueConsumer

  # ----------------------------------------------------
  # Lambda Layer
  # ----------------------------------------------------
  LambdaAutoReservationLayer:
    Type: AWS::Lambda::LayerVersion
    Properties: 
      CompatibleRuntimes: 
        - nodejs12.x
      Content: 
        S3Bucket: !Sub ${NameTag}-${EnvName}-lambda
        S3Key: !Sub ${ObjectKeyPrefix}/Layer/CommonLayer/Deploy.zip
      LayerName: !Sub ${NameTag}-${EnvName}-AutoReservationLayer

#################################
# Outputs
#################################
Outputs:
  LambdaScheduleQueuerArn:
    Value: !GetAtt LambdaScheduleQueuer.Arn
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaScheduleQueuerArn
  LambdaScheduleQueuerFunctionName:
    Value: !Ref LambdaScheduleQueuer
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaScheduleQueuerFunctionName
  LambdaDailyScheduleCreatorArn:
    Value: !GetAtt LambdaDailyScheduleCreator.Arn
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaDailyScheduleCreatorArn
  LambdaDailyScheduleCreatorFunctionName:
    Value: !Ref LambdaDailyScheduleCreator
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaDailyScheduleCreatorFunctionName
  LambdaDailyScheduleQueuerArn:
    Value: !GetAtt LambdaDailyScheduleQueuer.Arn
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaDailyScheduleQueuerArn
  LambdaDailyScheduleQueuerFunctionName:
    Value: !Ref LambdaDailyScheduleQueuer
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaDailyScheduleQueuerFunctionName
  LambdaDailyScheduleQueueConsumerArn:
    Value: !GetAtt LambdaDailyScheduleQueueConsumer.Arn
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaDailyScheduleQueueConsumerArn
  LambdaDailyScheduleQueueConsumerFunctionName:
    Value: !Ref LambdaDailyScheduleQueueConsumer
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaDailyScheduleQueueConsumerFunctionName
