AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda

######################################################
# Parameters:
######################################################
Parameters:
  ObjectKeyPrefix:
    Type: String

######################################################
# Resources
######################################################
Resources:
  LambdaSessionMaintainerScheduleEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: ’schedule event for lambda session maintainer’
      ScheduleExpression: 'cron(0/30 * * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !ImportValue LambdaSessionMaintainerArn
          Id: schedule-session-maintenance-target
  LambdaSessionMaintainerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !ImportValue LambdaSessionMaintainerFunctionName
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaSessionMaintainerScheduleEvent.Arn