AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda

######################################################
# Parameters:
######################################################
Parameters:
  ObjectKeyPrefix:
    Type: String
  NameTag:
    Type: String
    Default: neo-cycle
    AllowedValues:
      - neo-cycle
  EnvName:
    Type: String
    AllowedValues:
      - dev
      - prod

######################################################
# Resources
######################################################
Resources:
  LambdaSessionMaintainerScheduleEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: ’schedule event for lambda session maintainer’
      ScheduleExpression: 'cron(0/30 * * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !ImportValue
            Fn::Sub: ${NameTag}-${EnvName}-LambdaSessionMaintainerArn
          Id: schedule-session-maintenance-target
  LambdaSessionMaintainerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-LambdaSessionMaintainerFunctionName
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaSessionMaintainerScheduleEvent.Arn

  LambdaScheduleQueuerScheduleEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: ’schedule event for lambda ScheduleQueuer’
      ScheduleExpression: 'cron(50 14 * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !ImportValue
            Fn::Sub: ${NameTag}-${EnvName}-LambdaScheduleQueuerArn
          Id: schedule-schedule-queuer-target

  LambdaScheduleQueuerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-LambdaScheduleQueuerFunctionName
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleQueuerScheduleEvent.Arn

  LambdaDailyScheduleQueuerScheduleEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: ’schedule event for lambda DailyScheduleQueuer’
      ScheduleExpression: 'cron(7/10 * * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !ImportValue
            Fn::Sub: ${NameTag}-${EnvName}-LambdaDailyScheduleQueuerArn
          Id: schedule-schedule-queuer-target

  LambdaDailyScheduleQueuerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-LambdaDailyScheduleQueuerFunctionName
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaDailyScheduleQueuerScheduleEvent.Arn