AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda

######################################################
# Parameters:
######################################################
Parameters:
  ObjectKeyPrefix:
    Type: String
  NameTag:
    Type: String
    Default: neo-cycle
    AllowedValues:
      - neo-cycle
  EnvName:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Enter profile.

######################################################
# Resources
######################################################
Resources:
  LambdaUserInitializer:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${NameTag}-${EnvName}-lambda
        S3Key: !Sub ${ObjectKeyPrefix}/UserInitializer/Deploy.zip
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
      FunctionName: !Sub ${NameTag}-${EnvName}-UserInitializer
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-RoleUserInitializerArn
      Runtime: nodejs12.x
      Timeout: 10
      ReservedConcurrentExecutions: 10

#################################
# Outputs
#################################
Outputs:
  LambdaUserInitializerArn:
    Value: !GetAtt LambdaUserInitializer.Arn
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaUserInitializerArn
  LambdaUserInitializerName:
    Value: !Ref LambdaUserInitializer
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaUserInitializerName