AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda

######################################################
# Parameters:
######################################################
Parameters:
  ObjectKeyPrefix:
    Type: String
  NameTag:
    Type: String
    Default: neo-cycle
    AllowedValues:
      - neo-cycle
  EnvName:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Enter profile.
  SlackWebhookUrlForLoginMonitoring:
    Type: String

######################################################
# Resources
######################################################
Resources:
  LambdaUserInitializer:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${NameTag}-${EnvName}-lambda
        S3Key: !Sub ${ObjectKeyPrefix}/UserInitializer/Deploy.zip
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
      FunctionName: !Sub ${NameTag}-${EnvName}-UserInitializer
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-RoleUserInitializerArn
      Runtime: nodejs12.x
      Timeout: 10
      ReservedConcurrentExecutions: 10

  LambdaUserMigrator:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${NameTag}-${EnvName}-lambda
        S3Key: !Sub ${ObjectKeyPrefix}/UserMigrator/Deploy.zip
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
          SLACK_WEBHOOK_URL_FOR_LOGIN_MONITORING: !Ref SlackWebHookUrlForLoginMonitoring
      FunctionName: !Sub ${NameTag}-${EnvName}-UserMigrator
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-RoleUserMigratorArn
      Runtime: nodejs12.x
      Timeout: 10
      ReservedConcurrentExecutions: 10


  LambdaPostAuthenticator:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${NameTag}-${EnvName}-lambda
        S3Key: !Sub ${ObjectKeyPrefix}/PostAuthenticator/Deploy.zip
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
          SLACK_WEBHOOK_URL_FOR_LOGIN_MONITORING: !Ref SlackWebHookUrlForLoginMonitoring
      FunctionName: !Sub ${NameTag}-${EnvName}-PostAuthenticator
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue
        Fn::Sub: ${NameTag}-${EnvName}-RolePostAuthenticatorArn
      Runtime: nodejs12.x
      Timeout: 10
      ReservedConcurrentExecutions: 10
#################################
# Outputs
#################################
Outputs:
  LambdaUserInitializerArn:
    Value: !GetAtt LambdaUserInitializer.Arn
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaUserInitializerArn
  LambdaUserInitializerName:
    Value: !Ref LambdaUserInitializer
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaUserInitializerName
  LambdaUserMigratorArn:
    Value: !GetAtt LambdaUserMigrator.Arn
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaUserMigratorArn
  LambdaUserMigratorName:
    Value: !Ref LambdaUserMigrator
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaUserMigratorName
  LambdaPostAuthenticatorArn:
    Value: !GetAtt LambdaPostAuthenticator.Arn
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaPostAuthenticatorArn
  LambdaPostAuthenticatorName:
    Value: !Ref LambdaPostAuthenticator
    Export:
      Name: !Sub ${NameTag}-${EnvName}-LambdaPostAuthenticatorName      