AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda

######################################################
# Parameters:
######################################################
Parameters:
  ObjectKeyPrefix:
    Type: String

######################################################
# Resources
######################################################
Resources:
  LambdaSessionMaintainer:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: neo-cycle-lambda
        S3Key: !Sub
          - ${ObjectKeyPrefix}/SessionMaintainer/Deploy.zip
          - {
            ObjectKeyPrefix: !Ref ObjectKeyPrefix
          }
      FunctionName: SessionMaintainer
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue RoleSessionMaintainerArn
      Runtime: nodejs12.x
      Timeout: 10

  LambdaParkingRetriever:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: neo-cycle-lambda
        S3Key: !Sub
          - ${ObjectKeyPrefix}/ParkingRetriever/Deploy.zip
          - {
            ObjectKeyPrefix: !Ref ObjectKeyPrefix
          }
      Environment:
        Variables:
          PARKING_IDS: 10124,10077,10507
      FunctionName: ParkingRetriever
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue RoleParkingRetrieverArn
      Runtime: nodejs12.x
      Timeout: 10

  LambdaReservationMaker:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: neo-cycle-lambda
        S3Key: !Sub
          - ${ObjectKeyPrefix}/ReservationMaker/Deploy.zip
          - {
            ObjectKeyPrefix: !Ref ObjectKeyPrefix
          }
      FunctionName: ReservationMaker
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue RoleReservationMakerArn
      Runtime: nodejs12.x
      Timeout: 10

  LambdaReservationCanceller:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: neo-cycle-lambda
        S3Key: !Sub
          - ${ObjectKeyPrefix}/ReservationCanceller/Deploy.zip
          - {
            ObjectKeyPrefix: !Ref ObjectKeyPrefix
          }
      FunctionName: ReservationCanceller
      Handler: index.handler
      ReservedConcurrentExecutions: 1
      Role: !ImportValue RoleReservationCancellerArn
      Runtime: nodejs12.x
      Timeout: 10

#################################
# Outputs
#################################
Outputs:
  LambdaSessionMaintainerArn:
    Value: !GetAtt LambdaSessionMaintainer.Arn
    Export:
      Name: LambdaSessionMaintainerArn
  LambdaSessionMaintainerFunctionName:
    Value: !Ref LambdaSessionMaintainer
    Export:
      Name: LambdaSessionMaintainerFunctionName
  LambdaParkingRetrieverArn:
    Value: !GetAtt LambdaParkingRetriever.Arn
    Export:
      Name: LambdaParkingRetrieverArn
  LambdaParkingRetrieverFunctionName:
    Value: !Ref LambdaParkingRetriever
    Export:
      Name: LambdaParkingRetrieverFunctionName
  LambdaReservationMakerArn:
    Value: !GetAtt LambdaReservationMaker.Arn
    Export:
      Name: LambdaReservationMakerArn
  LambdaReservationMakerFunctionName:
    Value: !Ref LambdaReservationMaker
    Export:
      Name: LambdaReservationMakerFunctionName
  LambdaReservationCancellerArn:
    Value: !GetAtt LambdaReservationCanceller.Arn
    Export:
      Name: LambdaReservationCancellerArn
  LambdaReservationCancellerFunctionName:
    Value: !Ref LambdaReservationCanceller
    Export:
      Name: LambdaReservationCancellerFunctionName