AWSTemplateFormatVersion: "2010-09-09"

######################################################
# Parameters:
######################################################
Parameters:
  EnvName:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Enter profile.

######################################################
# Mappings:
######################################################
Mappings:
  StackConfig:
    ManagedPolicyArns:
      AWSLambdaBasicExecutionRole: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    NameTag:
      Value: neo-cycle

######################################################
# Resources:
######################################################
Resources:
  #-----------------------
  # ポリシー作成
  #-----------------------
  NeoCycleSessionTablePutItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to put item into session dynamodb 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/neo-cycle-SESSION"

  NeoCycleSessionTableGetItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to get item from session dynamodb 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/neo-cycle-SESSION"

  NeoCycleGetParameterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to get parameter from ssm
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ssm:getParameter
            Resource:
              - arn:aws:ssm:ap-northeast-1:010660485109:parameter/neo-cycle/memberId
              - arn:aws:ssm:ap-northeast-1:010660485109:parameter/neo-cycle/password
              - arn:aws:ssm:ap-northeast-1:010660485109:parameter/neo-cycle/php-url

  #-----------------------
  # ロールの作成
  #-----------------------
  RoleSessionMaintainer:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-session-maintainer-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleSessionTablePutItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
  
  RoleParkingRetriever:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-parking-retriever-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleSessionTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  RoleReservationMaker:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-reservation-maker-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleSessionTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  RoleReservationCanceller:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-reservation-canceller-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleSessionTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  RoleStatusChecker:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-status-checker-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleSessionTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

#################################
# Outputs
#################################
Outputs:
  RoleSessionMaintainerArn:
    Value: !GetAtt RoleSessionMaintainer.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-SessionMaintainerRoleArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleParkingRetrieverArn:
    Value: !GetAtt RoleParkingRetriever.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-ParkingRetrieverRoleArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleReservationMakerArn:
    Value: !GetAtt RoleReservationMaker.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-ReservationMakerRoleArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleReservationCancellerArn:
    Value: !GetAtt RoleReservationCanceller.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-ReservationCancellerRoleArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleStatusCheckerArn:
    Value: !GetAtt RoleStatusChecker.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-StatusCheckerRoleArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }