AWSTemplateFormatVersion: "2010-09-09"

######################################################
# Parameters:
######################################################
Parameters:
  EnvName:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Enter profile.
  NameTag:
    Type: String
    Default: neo-cycle
    AllowedValues:
      - neo-cycle
######################################################
# Mappings:
######################################################
Mappings:
  StackConfig:
    ManagedPolicyArns:
      AWSLambdaBasicExecutionRole: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    NameTag:
      Value: neo-cycle

######################################################
# Resources:
######################################################
Resources:
  #-----------------------
  # ポリシー作成
  #-----------------------
  NeoCycleUserTablePutItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to put item into user dynamodb 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${NameTag}-${EnvName}-USER"

  NeoCycleUserTableGetItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to get item from user dynamodb 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Scan
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${NameTag}-${EnvName}-USER"

  NeoCycleUserTableUpdateItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to update item in user dynamodb 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:UpdateItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${NameTag}-${EnvName}-USER"

  NeoCycleSessionTablePutItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to put item into session dynamodb 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${NameTag}-${EnvName}-SESSION"

  NeoCycleSessionTableGetItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to get item from session dynamodb 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${NameTag}-${EnvName}-SESSION"

  NeoCycleCommonSessionTablePutItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to put item into common session dynamodb
      ManagedPolicyName: !Sub ${NameTag}-${EnvName}-iam-NeoCycleCommonSessionTablePutItemPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${NameTag}-common-SESSION"

  NeoCycleCommonSessionTableGetItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to get item from common session dynamodb
      ManagedPolicyName: !Sub ${NameTag}-${EnvName}-iam-NeoCycleCommonSessionTableGetItemPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${NameTag}-common-SESSION"

  NeoCycleGetParameterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to get parameter from ssm
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ssm:getParameter
            Resource:
              - arn:aws:ssm:ap-northeast-1:010660485109:parameter/neo-cycle/php-url
              - !Sub arn:aws:ssm:ap-northeast-1:010660485109:parameter/neo-cycle/${EnvName}/memberId
              - !Sub arn:aws:ssm:ap-northeast-1:010660485109:parameter/neo-cycle/${EnvName}/password

  NeoCycleRekognitionDetectTextPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to detect text on rekognition
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - rekognition:DetectText
            Resource:
              - "*"

  NeoCycleDynamoDBStreamReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: authorize to read dynamodb stream
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:ListStreams
            Resource:
              - !Sub arn:aws:dynamodb:ap-northeast-1:010660485109:table/${NameTag}-common-SESSION/stream/*

  #-----------------------
  # ロールの作成
  #-----------------------
  RoleSessionMaintainer:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-session-maintainer-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleSessionTablePutItemPolicy
        - !Ref NeoCycleUserTableGetItemPolicy
        - !Ref NeoCycleCommonSessionTablePutItemPolicy
        - !Ref NeoCycleCommonSessionTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  RoleSessionSpreader:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-session-spreader-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleSessionTablePutItemPolicy
        - !Ref NeoCycleUserTableGetItemPolicy
        - !Ref NeoCycleCommonSessionTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
        - !Ref NeoCycleDynamoDBStreamReadPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
  
  RoleParkingRetriever:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-parking-retriever-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleUserTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  RoleReservationMaker:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-reservation-maker-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleUserTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  RoleReservationCanceller:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-reservation-canceller-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleUserTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  RoleStatusChecker:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-status-checker-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleUserTableGetItemPolicy
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  RoleParkingNearbyRetriever:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-parking-nearby-retriever-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  RoleUserInitializer:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-user-initializer-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleUserTablePutItemPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com              

  RoleParkingRegisterer:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-parking-registerer-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleGetParameterPolicy
        - !Ref NeoCycleUserTableUpdateItemPolicy
        - !Ref NeoCycleUserTableGetItemPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com   

  RoleUserMigrator:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-user-migrator-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleGetParameterPolicy
        - !Ref NeoCycleUserTablePutItemPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com


  RolePostAuthenticator:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-post-authenticator-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleGetParameterPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com 

  RoleBikeAvailableRetriever:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-bike-available-retriever-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleGetParameterPolicy
        - !Ref NeoCycleUserTableGetItemPolicy
        - !Ref NeoCycleSessionTableGetItemPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com 

  RoleBikeDetector:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${NameTag}-${EnvName}-bike-detector-role
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      ManagedPolicyArns:
        - !FindInMap [StackConfig, ManagedPolicyArns, AWSLambdaBasicExecutionRole]
        - !Ref NeoCycleRekognitionDetectTextPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com 
#################################
# Outputs
#################################
Outputs:
  RoleSessionMaintainerArn:
    Value: !GetAtt RoleSessionMaintainer.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleSessionMaintainerArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleSessionSpreaderArn:
    Value: !GetAtt RoleSessionSpreader.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleSessionSpreaderArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleParkingRetrieverArn:
    Value: !GetAtt RoleParkingRetriever.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleParkingRetrieverArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleReservationMakerArn:
    Value: !GetAtt RoleReservationMaker.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleReservationMakerArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleReservationCancellerArn:
    Value: !GetAtt RoleReservationCanceller.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleReservationCancellerArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleStatusCheckerArn:
    Value: !GetAtt RoleStatusChecker.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleStatusCheckerArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      
  RoleParkingNearbyRetrieverArn:
    Value: !GetAtt RoleParkingNearbyRetriever.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleParkingNearbyRetrieverArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleUserInitializerArn:
    Value: !GetAtt RoleUserInitializer.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleUserInitializerArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleParkingRegistererArn:
    Value: !GetAtt RoleParkingRegisterer.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleParkingRegistererArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleUserMigratorArn:
    Value: !GetAtt RoleUserMigrator.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleUserMigratorArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RolePostAuthenticatorArn:
    Value: !GetAtt RolePostAuthenticator.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RolePostAuthenticatorArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleBikeAvailableRetrieverArn:
    Value: !GetAtt RoleBikeAvailableRetriever.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleBikeAvailableRetrieverArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }

  RoleBikeDetectorArn:
    Value: !GetAtt RoleBikeDetector.Arn
    Export:
      Name: !Sub
        - ${NameTag}-${EnvName}-RoleBikeDetectorArn
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }