AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Amazon Certificate Manager

######################################################
# Parameters:
######################################################
Parameters:
  DomainName:
    Type: String
    Default: 'neo-cycle.com'
  EnvName:
    Type: String
    AllowedValues:
      - dev
      - it1
      - it2
      - it3
      - it4
      - it5
      - staging1
      - staging2
      - staging3
      - staging4
      - staging5
      - prod
  NameTag:
    Type: String
    Default: neo-cycle
  SubDomain:
    Type: String

######################################################
# Resources:
###################################################### 
Resources:
  NeoCycleCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        Aliases: 
          - !Sub ${SubDomain}.${DomainName}
        DefaultCacheBehavior:
          DefaultTTL: 1
          MaxTTL: 1
          MinTTL: 1
          SmoothStreaming: false
          ForwardedValues:
             QueryString: false
          TargetOriginId: !Sub S3-${SubDomain}.neo-cycle.com
          ViewerProtocolPolicy: https-only
        DefaultRootObject: index.html
        Enabled: true
        IPV6Enabled: false
        Origins: 
          - DomainName: !Sub ${SubDomain}.neo-cycle.com.s3.amazonaws.com
            Id: !Sub S3-${SubDomain}.neo-cycle.com
            S3OriginConfig: 
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        ViewerCertificate: 
          AcmCertificateArn: !ImportValue
            Fn::Sub: ${NameTag}-certificate
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        HttpVersion: http2
  
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub neo-cycle-${EnvName}