AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API Gateway

######################################################
# Parameters:
######################################################
Parameters:
  NameTag:
    Type: String
    Default: neo-cycle
    AllowedValues:
      - neo-cycle
  EnvName:
    Type: String
    AllowedValues:
      - dev
      - it1
      - it2
      - it3
      - it4
      - it5
      - staging1
      - staging2
      - staging3
      - staging4
      - staging5
      - prod
    Description: Enter profile.

######################################################
# Mappings
######################################################
Mappings:
  StackConfig:
    NameTag:
      Value: neo-cycle

######################################################
# Resources
######################################################
Resources:
  ######################################################
  # Rest API
  ######################################################
  NeoCycleRestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 
        - ${NameTag}-${EnvName}-api-gateway
        - {
          NameTag: !FindInMap [ StackConfig, NameTag, Value ],
          EnvName: !Ref EnvName
        }
      EndpointConfiguration:
        Types:
          - EDGE


  ######################################################
  # Parkings
  #   - Resource
  #     - path: /parkings
  #   - Method
  #     - POST
  #     - OPTION(for enable CORS)
  #   - Lambda Permission
  ######################################################
  ParkingsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref NeoCycleRestAPI
      ParentId: !GetAtt
        - NeoCycleRestAPI
        - RootResourceId
      PathPart: parkings

  ParkingsPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref ParkingsResource
      RestApiId: !Ref NeoCycleRestAPI
      MethodResponses: 
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin" : true
      Integration:
        Type: AWS
        Uri: !Sub
          - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${LambdaParkingRetrieverArn}/invocations
          - {
            LambdaParkingRetrieverArn: {
              'Fn::ImportValue':
                !Sub "${NameTag}-${EnvName}-LambdaParkingRetrieverArn"
            }
          }
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              'method.response.header.Access-Control-Allow-Origin' : "'*'" # 中身を一重引用符で囲う
    DependsOn: LambdaParkingsRegistererPermission

  ParkingsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: NeoCycleRestAPI
      ResourceId:
        Ref: ParkingsResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
          method.response.header.Access-Control-Allow-Headers: false
          method.response.header.Access-Control-Allow-Methods: false
          method.response.header.Access-Control-Allow-Origin: false
    DependsOn: ParkingsResource

  LambdaParkingsRegistererPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !ImportValue
        Fn::Sub:
          - ${NameTag}-${EnvName}-LambdaParkingRetrieverFunctionName
          - {
            NameTag: !FindInMap [ StackConfig, NameTag, Value ],
            EnvName: !Ref EnvName
          }
      Principal: apigateway.amazonaws.com

  ######################################################
  # Reservation
  #   - Resource
  #     - path: /reservation
  #   - Method
  #     - POST
  #     - OPTION(for enable CORS)
  #   - Lambda Permission
  ######################################################
  ReservationResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref NeoCycleRestAPI
      ParentId: !GetAtt
        - NeoCycleRestAPI
        - RootResourceId
      PathPart: reservation

  ReservationPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref ReservationResource
      RestApiId: !Ref NeoCycleRestAPI
      MethodResponses: 
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin" : true
      Integration:
        Type: AWS
        Uri: !Sub
          - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${LambdaReservationMakerArn}/invocations
          - {
            LambdaReservationMakerArn: {
              'Fn::ImportValue':
                !Sub "${NameTag}-${EnvName}-LambdaReservationMakerArn"
            }
          }
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              'method.response.header.Access-Control-Allow-Origin' : "'*'" # 中身を一重引用符で囲う
    DependsOn: LambdaReservationMakerPermission

  ReservationOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: NeoCycleRestAPI
      ResourceId:
        Ref: ReservationResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
          method.response.header.Access-Control-Allow-Headers: false
          method.response.header.Access-Control-Allow-Methods: false
          method.response.header.Access-Control-Allow-Origin: false
    DependsOn: ReservationResource

  LambdaReservationMakerPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !ImportValue
        Fn::Sub:
          - ${NameTag}-${EnvName}-LambdaReservationMakerFunctionName
          - {
            NameTag: !FindInMap [ StackConfig, NameTag, Value ],
            EnvName: !Ref EnvName
          }
      Principal: apigateway.amazonaws.com

  ######################################################
  # Cancellation
  #   - Resource
  #     - path: /cancellation
  #   - Method
  #     - POST
  #     - OPTION(for enable CORS)
  #   - Lambda Permission
  ######################################################
  CancellationResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref NeoCycleRestAPI
      ParentId: !GetAtt
        - NeoCycleRestAPI
        - RootResourceId
      PathPart: cancellation

  CancellationPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref CancellationResource
      RestApiId: !Ref NeoCycleRestAPI
      MethodResponses: 
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin" : true
      Integration:
        Type: AWS
        Uri: !Sub
          - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${LambdaReservationCancellerArn}/invocations
          - {
            LambdaReservationCancellerArn: {
              'Fn::ImportValue':
                !Sub "${NameTag}-${EnvName}-LambdaReservationCancellerArn"
            }
          }
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              'method.response.header.Access-Control-Allow-Origin' : "'*'" # 中身を一重引用符で囲う
    DependsOn: LambdaReservationCancellerPermission

  CancellationOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: NeoCycleRestAPI
      ResourceId:
        Ref: CancellationResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
          method.response.header.Access-Control-Allow-Headers: false
          method.response.header.Access-Control-Allow-Methods: false
          method.response.header.Access-Control-Allow-Origin: false
    DependsOn: CancellationResource

  LambdaReservationCancellerPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !ImportValue
        Fn::Sub:
          - ${NameTag}-${EnvName}-LambdaReservationCancellerFunctionName
          - {
            NameTag: !FindInMap [ StackConfig, NameTag, Value ],
            EnvName: !Ref EnvName
          }
      Principal: apigateway.amazonaws.com

  ######################################################
  # Status
  #   - Resource
  #     - path: /status
  #   - Method
  #     - POST
  #     - OPTION(for enable CORS)
  #   - Lambda Permission
  ######################################################
  StatusResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref NeoCycleRestAPI
      ParentId: !GetAtt
        - NeoCycleRestAPI
        - RootResourceId
      PathPart: status

  StatusPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref StatusResource
      RestApiId: !Ref NeoCycleRestAPI
      MethodResponses: 
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin" : true
      Integration:
        Type: AWS
        Uri: !Sub
          - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${LambdaStatusCheckerArn}/invocations
          - {
            LambdaStatusCheckerArn: {
              'Fn::ImportValue':
                !Sub "${NameTag}-${EnvName}-LambdaStatusCheckerArn"
            }
          }
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              'method.response.header.Access-Control-Allow-Origin' : "'*'" # 中身を一重引用符で囲う
    DependsOn: LambdaStatusCheckerPermission

  StatusOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: NeoCycleRestAPI
      ResourceId:
        Ref: StatusResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
          method.response.header.Access-Control-Allow-Headers: false
          method.response.header.Access-Control-Allow-Methods: false
          method.response.header.Access-Control-Allow-Origin: false
    DependsOn: StatusResource

  LambdaStatusCheckerPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !ImportValue
        Fn::Sub:
          - ${NameTag}-${EnvName}-LambdaStatusCheckerFunctionName
          - {
            NameTag: !FindInMap [ StackConfig, NameTag, Value ],
            EnvName: !Ref EnvName
          }
      Principal: apigateway.amazonaws.com