AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DynamoDB setup

######################################################
# Parameters:
######################################################
Parameters:
  NameTag:
    Type: String
    Default: neo-cycle
    AllowedValues:
      - neo-cycle
  EnvName:
    Type: String
    AllowedValues:
      - common
    Description: Enter profile.

######################################################
# Resources
######################################################
Resources:
  #----------------------------------------------
  # SESSION
  #----------------------------------------------
  SESSION:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: memberId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: memberId
          AttributeType: S
      TableName: !Sub ${NameTag}-${EnvName}-SESSION
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true 
      StreamSpecification:
        StreamViewType: NEW_IMAGE

#################################
# Outputs
#################################
Outputs:
  SessionTableStramsArn:
    Value: !GetAtt SESSION.StreamArn
    Export:
      Name: !Sub ${NameTag}-${EnvName}-SessionTableStreamArn